### ISSUE TITLE
Allure report cannot be generated

### ISSUE THREAD

**Issue by franckrasolo** [allure-examples/allure-scalatest-example#1]
Running `sbt clean test` on a 1.7 JVM produces the following error:

```
Reporter completed abruptly with an exception after receiving event: SuiteCompleted(Ordinal(0, 8),StackSpec,ru.yandex.qatools.allure.scalatest.StackSpec,Some(ru.yandex.qatools.allure.scalatest.StackSpec),Some(81),Some(MotionToSuppress),Some(TopOfClass(ru.yandex.qatools.allure.scalatest.StackSpec)),None,None,pool-7-thread-5,1401553790490).
ru.yandex.qatools.allure.exceptions.AllureException: Can't marshall test suite result
    at ru.yandex.qatools.allure.utils.AllureResultsUtils.writeTestSuiteResult(AllureResultsUtils.java:75)
    at ru.yandex.qatools.allure.Allure.fire(Allure.java:106)
    at ru.yandex.qatools.allure.scalatest.AllureReporter.testSuiteFinished(AllureReporter.scala:70)
    at ru.yandex.qatools.allure.scalatest.AllureReporter.apply(AllureReporter.scala:42)
    at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:240)
    at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:239)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:239)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.bind.PropertyException: name: com.sun.xml.bind.marshaller.CharacterEscapeHandler value: ru.yandex.qatools.allure.utils.XmlEscapeHandler@7bbcb88e
    at javax.xml.bind.helpers.AbstractMarshallerImpl.setProperty(AbstractMarshallerImpl.java:358)
    at com.sun.xml.internal.bind.v2.runtime.MarshallerImpl.setProperty(MarshallerImpl.java:527)
    at ru.yandex.qatools.allure.utils.AllureResultsUtils.writeTestSuiteResult(AllureResultsUtils.java:69)
    ... 8 more
```

**Comment by vania-pooh** [comment]
Thank you for the feedback. Unfortunately your issue duplicates this one: https://github.com/allure-framework/allure-scalatest/issues/3 Please post issues directly to [allure-scalatest](https://github.com/allure-framework/allure-scalatest) next time.

**Comment by franckrasolo** [comment]
Will do, thanks.
