### ISSUE TITLE
Compilation error on 1.6 JVM

### ISSUE THREAD

**Issue by franckrasolo** [allure-examples/allure-scalatest-example#2]
Running `sbt clean test` on a 1.6 JVM produces the following compilation error:

```
[info] Compiling 1 Scala source to ~/projects/scala/allure-scalatest-example/target/scala-2.10/test-classes...
java.lang.UnsupportedClassVersionError: ru/yandex/qatools/allure/events/TestCaseEvent : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2446)
    at java.lang.Class.getConstructor0(Class.java:2756)
    at java.lang.Class.newInstance0(Class.java:328)
    at java.lang.Class.newInstance(Class.java:310)
    at org.scalatest.tools.ReporterFactory.getCustomReporter(ReporterFactory.scala:30)
    at org.scalatest.tools.ReporterFactory.createCustomReporter(ReporterFactory.scala:201)
    at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:234)
    at org.scalatest.tools.ReporterFactory$$anonfun$createReportersFromConfigurations$1.apply(ReporterFactory.scala:242)
    at org.scalatest.tools.ReporterFactory$$anonfun$createReportersFromConfigurations$1.apply(ReporterFactory.scala:241)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:43)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:43)
    at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:241)
    at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:245)
    at org.scalatest.tools.Framework$ScalaTestRunner.<init>(Framework.scala:824)
    at org.scalatest.tools.Framework.runner(Framework.scala:1167)
    at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:487)
    at sbt.Defaults$$anonfun$createTestRunners$1.apply(Defaults.scala:482)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at sbt.Defaults$.createTestRunners(Defaults.scala:482)
    at sbt.Defaults$.allTestGroupsTask(Defaults.scala:493)
    at sbt.Defaults$$anonfun$testTasks$4.apply(Defaults.scala:361)
    at sbt.Defaults$$anonfun$testTasks$4.apply(Defaults.scala:361)
    at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:35)
    at scala.Function7$$anonfun$tupled$1.apply(Function7.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
[error] (test:executeTests) java.lang.UnsupportedClassVersionError: ru/yandex/qatools/allure/events/TestCaseEvent : Unsupported major.minor version 51.0
```

**Comment by vania-pooh** [comment]
Yes, that's because all Allure code is compiled with JDK 1.7.

**Comment by vania-pooh** [comment]
Added restriction about JDK version in allure-scalatest readme.
